In [2]:
import pandas as pd

df = pd.read_csv(
    r"/mnt/c/Users/KDT-18/Desktop/AI_study/미니 프로젝트_당뇨병예측/diabetes.csv"
)

print(df.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  


In [3]:
cols = ["BloodPressure", "BMI"]

# 세 컬럼 중 하나라도 0인 행을 모두 제거
df_clean = df[(df[cols] != 0).all(axis=1)]

print(df.shape)      # 원래 크기
print(df_clean.shape)  # 0인 행 제거 후 크기
print(df_clean.head())

(768, 9)
(729, 9)
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  


In [4]:
from sklearn.model_selection import train_test_split

# 1) 입력으로 사용할 컬럼들
feature_cols = [ "Pregnancies",
    "BloodPressure",
    "BMI",
    "DiabetesPedigreeFunction"
]
target=["Outcome"]
x = df[feature_cols]       # 입력 데이터프레임
y = df[target]    
# 2) 학습/테스트 분리
train_input, test_input, train_target, test_target = train_test_split(
   x,y,
    test_size=0.2,
    random_state=42
)

print(train_input.head())
print(train_target.head())

     Pregnancies  BloodPressure   BMI  DiabetesPedigreeFunction
60             2              0   0.0                     0.304
618            9             82  28.2                     1.282
346            1             46  28.7                     0.654
294            0             50  21.9                     0.254
231            6             80  46.2                     0.238
     Outcome
60         0
618        1
346        0
294        0
231        1


In [5]:
import numpy as np
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(rf, train_input, train_target,
                       return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector 

1.0 0.6792483006797282


In [6]:
rf.fit(train_input, train_target)
print(rf.feature_importances_)
print(train_input.head())

/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


[0.15959017 0.19412038 0.34984625 0.29644321]
     Pregnancies  BloodPressure   BMI  DiabetesPedigreeFunction
60             2              0   0.0                     0.304
618            9             82  28.2                     1.282
346            1             46  28.7                     0.654
294            0             50  21.9                     0.254
231            6             80  46.2                     0.238


In [7]:
rf=RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
print(rf.oob_score_)

/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


0.6644951140065146


In [8]:
#엑스트라트리 : 부트스트랩과 다르게 중복된 샘플 없음. 한번씩만 사용 -> 무작위로 분할! 진정한 랜덤, 진정한 과대적합 방지
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target,
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))
#연산 속도가 빠름!



/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector 

1.0 0.6808210049313608


In [18]:
et.fit(train_input, train_target)
print(et.feature_importances_)

/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


[0.1741412  0.21948697 0.33006678 0.27630506]


In [10]:
#그레디언트 부스팅: 깊이는 얕고, 경사하강법 적용 -> 결정트리를 계속 추가함
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier(random_state=42)
scores = cross_validate(gb, train_input, train_target,
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.8908780818969086 0.6906570705051313


/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning

In [11]:
gb=GradientBoostingClassifier(n_estimators=500, learning_rate=0.2,
                              random_state=42)
scores=cross_validate(gb, train_input, train_target,
                      return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))
#결정 트리 개수를 500개, 학습률 learning rate의 기본값은 0.1 인데 0.2로 상향함

/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning

1.0 0.6450753032120485


In [12]:
gb.fit(train_input, train_target)
print(gb.feature_importances_)

/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.13811545 0.09790514 0.36476092 0.39921849]


In [13]:
#그레디언트 부스팅에서 속도와 성능을 개선한게 히스토그램 기반 그레디언트 부스팅
#정형 데이터의 앙상블 중 가장 인기있음.
#특성을 255+1로 나눔으로써 노드 분할 시 최적의 노드를 빨리 찾을 수 있음->평행하게 주욱~ 늘려서 최적점 찾기
#XGBoost, LightGBM 있음!
from sklearn.ensemble import HistGradientBoostingClassifier
hgb=HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgb, train_input, train_target,
                        return_train_score=True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))
#여기서는 n_jobs 지정을 안해도 되는군...

/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/utils/validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/utils/validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/utils/validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/utils/validation.py:1406: DataConversionWarning: A column-v

0.98167916811551 0.6564574170331868


In [14]:
#특성중요도를 permutationJmportance () 함수로 계산해야하는 번거로움이 있음!
from sklearn.inspection import permutation_importance
hgb.fit(train_input, train_target)
result=permutation_importance(hgb, train_input, train_target,
                              n_repeats=10, random_state=42, n_jobs=-1)
print(result.importances_mean)
#훈련레벨에서 중요도 체크

/home/user1/miniconda3/envs/ai-study/lib/python3.10/site-packages/sklearn/utils/validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.13827362 0.13843648 0.27638436 0.24527687]


In [19]:
result = permutation_importance(hgb, test_input, test_target,
                                n_repeats=10, random_state=42, n_jobs=-1)
print(result.importances_mean)
#테스트레벨에서 중요도 체크

[0.03441558 0.02402597 0.08961039 0.0487013 ]


In [20]:
#최종 성능 확인하자!!
hgb.score(train_input, train_target)


0.9788273615635179

In [17]:
from xgboost import XGBClassifier
xgb=XGBClassifier(tree_method='hist', random_state=42)
scores=cross_validate(xgb, train_input, train_target,
                      return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

1.0 0.6434359589497535
